///////////////////////////////////////////////////////////
//  Profile.cs
//  Implementation of the Class Profile
//  Generated by Enterprise Architect
//  Created on:      09-Jun-2016 8:23:02 AM
//  Original author: ali-laptop
///////////////////////////////////////////////////////////

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Comision.Model.Enum;

namespace Comision.Model.Domain.UserDomain
{
    /// <summary>
    /// <span dir="rtl">پروفايل</span>
    /// </summary>
    public class Profile
    {
        /// <summary>
        /// <span dir="rtl">کلید اصلی و کلید خارجی</span>
        /// </summary>
        public long PersonId { get; set; }
        public virtual Person Person { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }

        [NotMapped]
        public string FullName => Name + " " + Family;

        [Index("IX_NationalCode", IsUnique = true)]
        public string NationalCode { get; set; }

        /// <summary>
        /// شماره شناسنامه
        /// </summary>
        public string BirthcertificateNumber { get; set; }
        public string Mobile { get; set; }

        [UIHint("PersianDatePicker")]
        public DateTime? BrithDate { get; set; }
        public Gender Gender { get; set; }
        public string Avatar { get; set; }
        public string EmailUnivercity { get; set; }
        public string AddressWork { get; set; }
        public string PhoneWork { get; set; }
        public string WebSite { get; set; }

        //[AllowHtml]
        public string Description { get; set; }

        public Profile() { }

    }//end Profile
}