///////////////////////////////////////////////////////////
//  Role.cs
//  Implementation of the Class Role
//  Generated by Enterprise Architect
//  Created on:      09-Jun-2016 8:23:14 AM
//  Original author: ali-laptop
///////////////////////////////////////////////////////////

using System.ComponentModel.DataAnnotations.Schema;
using System.Xml.Linq;
//using Comision.Helper;
using Comision.Model.Enum;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Comision.Model.Domain.UserDomain
{
    /// <summary>
    /// <span dir="rtl">фод</span>
    /// </summary>
    public class Role : IdentityRole<long, UserRole>
    {
        [Index("IX_role", IsUnique = true, Order = 1)]
        public long? CentralOrganizationId { get; set; }
        public virtual CentralOrganization CentralOrganization { get; set; }

        [Index("IX_role", IsUnique = true, Order = 2)]
        public long? BranchProvinceId { get; set; }
        public virtual BranchProvince BranchProvince { get; set; }

        [Index("IX_role", IsUnique = true, Order = 3)]
        public long? UniversityId { get; set; }
        public virtual University University { get; set; }

        [Index("IX_role", IsUnique = true, Order = 4)]
       public string NameFa { get; set; }
        public RoleType RoleType { get; set; }
        public string XmlRoleAccess { get; set; }
        public XElement XmlValueWrapper
        {
            get { return XElement.Parse(XmlRoleAccess); }
            set { XmlRoleAccess = value.ToString(); }
        }

        public Role() { }
        public Role(long levelId, RoleType roleType)
        {
            RoleType = roleType;
            Name = roleType.ToString();
            NameFa = roleType.ToString();//roleType.GetDescription();
            switch (roleType)
            {
                case RoleType.AdminCentral:
                    CentralOrganizationId = levelId;
                    break;
                case RoleType.AdminBranch:
                    BranchProvinceId = levelId;
                    break;
                default:
                    UniversityId = levelId;
                    break;
            }
        }

    }//end Role
}