///////////////////////////////////////////////////////////
//  User.cs
//  Implementation of the Class User
//  Generated by Enterprise Architect
//  Created on:      09-Jun-2016 8:23:34 AM
//  Original author: ali-laptop
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Comision.Model.Domain.UserDomain
{
    /// <summary>
    /// <span dir="rtl">کاربر</span>
    /// </summary>
    public class User : IdentityUser<long,UserLogin, UserRole, UserClaim>
    {
        ///// <summary>
        ///// <span dir="rtl">کلید اصلی و کلید خارجی</span>
        ///// </summary>
        //public long IdPerson { get; set; }
        public virtual Person Person { get; set; }
        public long AuthenticationId { get; set; }
        public virtual Authentication Authentication { get; set; }

        /// <summary>
        /// لیست اختیارات کاربر
        /// </summary>
        public virtual ICollection<UserPost> UserPosts { get; set; }
        //public bool IsOnline { get; set; }
        //public UserState State { get; set; }
        public User() { }

    }//end User
}