// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Comision.Ui.Areas.Admin.Controllers
{
    public partial class AssignmentPostUserController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AssignmentPostUserController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddOrUpdateAssignmentPostUser()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddOrUpdateAssignmentPostUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetListPostofUser()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetListPostofUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetListStructure()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetListStructure);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteAssignmentPostUser()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteAssignmentPostUser);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AssignmentPostUserController Actions { get { return MVC.Admin.AssignmentPostUser; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "AssignmentPostUser";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "AssignmentPostUser";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string AddOrUpdateAssignmentPostUser = "AddOrUpdateAssignmentPostUser";
            public readonly string GetListPostofUser = "GetListPostofUser";
            public readonly string GetListUser = "GetListUser";
            public readonly string GetListPostSigner = "GetListPostSigner";
            public readonly string GetListStructure = "GetListStructure";
            public readonly string DeleteAssignmentPostUser = "DeleteAssignmentPostUser";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string AddOrUpdateAssignmentPostUser = "AddOrUpdateAssignmentPostUser";
            public const string GetListPostofUser = "GetListPostofUser";
            public const string GetListUser = "GetListUser";
            public const string GetListPostSigner = "GetListPostSigner";
            public const string GetListStructure = "GetListStructure";
            public const string DeleteAssignmentPostUser = "DeleteAssignmentPostUser";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string personId = "personId";
        }
        static readonly ActionParamsClass_AddOrUpdateAssignmentPostUser s_params_AddOrUpdateAssignmentPostUser = new ActionParamsClass_AddOrUpdateAssignmentPostUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddOrUpdateAssignmentPostUser AddOrUpdateAssignmentPostUserParams { get { return s_params_AddOrUpdateAssignmentPostUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddOrUpdateAssignmentPostUser
        {
            public readonly string postPersonModel = "postPersonModel";
        }
        static readonly ActionParamsClass_GetListPostofUser s_params_GetListPostofUser = new ActionParamsClass_GetListPostofUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetListPostofUser GetListPostofUserParams { get { return s_params_GetListPostofUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetListPostofUser
        {
            public readonly string personId = "personId";
        }
        static readonly ActionParamsClass_GetListStructure s_params_GetListStructure = new ActionParamsClass_GetListStructure();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetListStructure GetListStructureParams { get { return s_params_GetListStructure; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetListStructure
        {
            public readonly string postId = "postId";
            public readonly string postType = "postType";
        }
        static readonly ActionParamsClass_DeleteAssignmentPostUser s_params_DeleteAssignmentPostUser = new ActionParamsClass_DeleteAssignmentPostUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteAssignmentPostUser DeleteAssignmentPostUserParams { get { return s_params_DeleteAssignmentPostUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteAssignmentPostUser
        {
            public readonly string personId = "personId";
            public readonly string postId = "postId";
            public readonly string postTypeId = "postTypeId";
            public readonly string levelId = "levelId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
            }
            public readonly string Index = "~/Areas/Admin/Views/AssignmentPostUser/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AssignmentPostUserController : Comision.Ui.Areas.Admin.Controllers.AssignmentPostUserController
    {
        public T4MVC_AssignmentPostUserController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long? personId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(long? personId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            IndexOverride(callInfo, personId);
            return callInfo;
        }

        [NonAction]
        partial void AddOrUpdateAssignmentPostUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Comision.Service.Model.PostPersonModel postPersonModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddOrUpdateAssignmentPostUser(Comision.Service.Model.PostPersonModel postPersonModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddOrUpdateAssignmentPostUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "postPersonModel", postPersonModel);
            AddOrUpdateAssignmentPostUserOverride(callInfo, postPersonModel);
            return callInfo;
        }

        [NonAction]
        partial void GetListPostofUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long personId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetListPostofUser(long personId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetListPostofUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            GetListPostofUserOverride(callInfo, personId);
            return callInfo;
        }

        [NonAction]
        partial void GetListUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetListUser()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetListUser);
            GetListUserOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetListPostSignerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetListPostSigner()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetListPostSigner);
            GetListPostSignerOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetListStructureOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long postId, Comision.Model.Enum.PostType postType);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetListStructure(long postId, Comision.Model.Enum.PostType postType)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetListStructure);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "postId", postId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "postType", postType);
            GetListStructureOverride(callInfo, postId, postType);
            return callInfo;
        }

        [NonAction]
        partial void DeleteAssignmentPostUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long personId, long postId, int postTypeId, long levelId);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteAssignmentPostUser(long personId, long postId, int postTypeId, long levelId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteAssignmentPostUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personId", personId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "postId", postId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "postTypeId", postTypeId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "levelId", levelId);
            DeleteAssignmentPostUserOverride(callInfo, personId, postId, postTypeId, levelId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
