// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Comision.Ui.Areas.Admin.Controllers
{
    public partial class MemberController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected MemberController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetMembers()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetMembers);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetDetails()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CreateMember()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateMember);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CreateDetail()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateDetail);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteMember()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteMember);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteDetail()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteDetail);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditMaster()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditMaster);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditDetail()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditDetail);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public MemberController Actions { get { return MVC.Admin.Member; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Member";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Member";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string GetMembers = "GetMembers";
            public readonly string GetDetails = "GetDetails";
            public readonly string GetListPersonel = "GetListPersonel";
            public readonly string CreateMember = "CreateMember";
            public readonly string CreateDetail = "CreateDetail";
            public readonly string DeleteMember = "DeleteMember";
            public readonly string DeleteDetail = "DeleteDetail";
            public readonly string EditMaster = "EditMaster";
            public readonly string EditDetail = "EditDetail";
            public readonly string GetPosts = "GetPosts";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string GetMembers = "GetMembers";
            public const string GetDetails = "GetDetails";
            public const string GetListPersonel = "GetListPersonel";
            public const string CreateMember = "CreateMember";
            public const string CreateDetail = "CreateDetail";
            public const string DeleteMember = "DeleteMember";
            public const string DeleteDetail = "DeleteDetail";
            public const string EditMaster = "EditMaster";
            public const string EditDetail = "EditDetail";
            public const string GetPosts = "GetPosts";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string requestType = "requestType";
        }
        static readonly ActionParamsClass_GetMembers s_params_GetMembers = new ActionParamsClass_GetMembers();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetMembers GetMembersParams { get { return s_params_GetMembers; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetMembers
        {
            public readonly string requestType = "requestType";
        }
        static readonly ActionParamsClass_GetDetails s_params_GetDetails = new ActionParamsClass_GetDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetDetails GetDetailsParams { get { return s_params_GetDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetDetails
        {
            public readonly string masterId = "masterId";
        }
        static readonly ActionParamsClass_CreateMember s_params_CreateMember = new ActionParamsClass_CreateMember();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateMember CreateMemberParams { get { return s_params_CreateMember; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateMember
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_CreateDetail s_params_CreateDetail = new ActionParamsClass_CreateDetail();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateDetail CreateDetailParams { get { return s_params_CreateDetail; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateDetail
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_DeleteMember s_params_DeleteMember = new ActionParamsClass_DeleteMember();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteMember DeleteMemberParams { get { return s_params_DeleteMember; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteMember
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeleteDetail s_params_DeleteDetail = new ActionParamsClass_DeleteDetail();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteDetail DeleteDetailParams { get { return s_params_DeleteDetail; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteDetail
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_EditMaster s_params_EditMaster = new ActionParamsClass_EditMaster();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditMaster EditMasterParams { get { return s_params_EditMaster; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditMaster
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_EditDetail s_params_EditDetail = new ActionParamsClass_EditDetail();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditDetail EditDetailParams { get { return s_params_EditDetail; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditDetail
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
            }
            public readonly string Index = "~/Areas/Admin/Views/Member/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_MemberController : Comision.Ui.Areas.Admin.Controllers.MemberController
    {
        public T4MVC_MemberController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Comision.Model.Enum.RequestType requestType);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(Comision.Model.Enum.RequestType requestType)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "requestType", requestType);
            IndexOverride(callInfo, requestType);
            return callInfo;
        }

        [NonAction]
        partial void GetMembersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Comision.Model.Enum.RequestType requestType);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetMembers(Comision.Model.Enum.RequestType requestType)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetMembers);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "requestType", requestType);
            GetMembersOverride(callInfo, requestType);
            return callInfo;
        }

        [NonAction]
        partial void GetDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long masterId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetDetails(long masterId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "masterId", masterId);
            GetDetailsOverride(callInfo, masterId);
            return callInfo;
        }

        [NonAction]
        partial void GetListPersonelOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetListPersonel()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetListPersonel);
            GetListPersonelOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateMemberOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Comision.Service.Model.MemberMasterModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateMember(Comision.Service.Model.MemberMasterModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateMember);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CreateMemberOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void CreateDetailOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Comision.Service.Model.MemberDetailModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateDetail(Comision.Service.Model.MemberDetailModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateDetail);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CreateDetailOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void DeleteMemberOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteMember(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteMember);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteMemberOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteDetailOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteDetail(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteDetail);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteDetailOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditMasterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Comision.Service.Model.MemberMasterModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditMaster(Comision.Service.Model.MemberMasterModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditMaster);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditMasterOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void EditDetailOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Comision.Service.Model.MemberDetailModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditDetail(Comision.Service.Model.MemberDetailModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditDetail);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditDetailOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void GetPostsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetPosts()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetPosts);
            GetPostsOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
