// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Comision.Ui.Controllers
{
    public partial class HomeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult GetPartialTextDefault()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetPartialTextDefault);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetSelectTextDefault()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetSelectTextDefault);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Error()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Error);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController Actions { get { return MVC.Home; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string About = "About";
            public readonly string Contact = "Contact";
            public readonly string GetPartialTextDefault = "GetPartialTextDefault";
            public readonly string GetSelectTextDefault = "GetSelectTextDefault";
            public readonly string Image = "Image";
            public readonly string Error = "Error";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string About = "About";
            public const string Contact = "Contact";
            public const string GetPartialTextDefault = "GetPartialTextDefault";
            public const string GetSelectTextDefault = "GetSelectTextDefault";
            public const string Image = "Image";
            public const string Error = "Error";
        }


        static readonly ActionParamsClass_GetPartialTextDefault s_params_GetPartialTextDefault = new ActionParamsClass_GetPartialTextDefault();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPartialTextDefault GetPartialTextDefaultParams { get { return s_params_GetPartialTextDefault; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPartialTextDefault
        {
            public readonly string divName = "divName";
            public readonly string textDefaultType = "textDefaultType";
            public readonly string idboxName = "idboxName";
            public readonly string textboxName = "textboxName";
        }
        static readonly ActionParamsClass_GetSelectTextDefault s_params_GetSelectTextDefault = new ActionParamsClass_GetSelectTextDefault();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetSelectTextDefault GetSelectTextDefaultParams { get { return s_params_GetSelectTextDefault; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetSelectTextDefault
        {
            public readonly string type = "type";
        }
        static readonly ActionParamsClass_Error s_params_Error = new ActionParamsClass_Error();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Error ErrorParams { get { return s_params_Error; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Error
        {
            public readonly string httpCode = "httpCode";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _GetPartialTextDefault = "_GetPartialTextDefault";
                public readonly string About = "About";
                public readonly string Contact = "Contact";
                public readonly string Index = "Index";
            }
            public readonly string _GetPartialTextDefault = "~/Views/Home/_GetPartialTextDefault.cshtml";
            public readonly string About = "~/Views/Home/About.cshtml";
            public readonly string Contact = "~/Views/Home/Contact.cshtml";
            public readonly string Index = "~/Views/Home/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_HomeController : Comision.Ui.Controllers.HomeController
    {
        public T4MVC_HomeController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AboutOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult About()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.About);
            AboutOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ContactOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Contact()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Contact);
            ContactOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetPartialTextDefaultOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, string divName, Comision.Model.Enum.TextDefaultType textDefaultType, string idboxName, string textboxName);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult GetPartialTextDefault(string divName, Comision.Model.Enum.TextDefaultType textDefaultType, string idboxName, string textboxName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetPartialTextDefault);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "divName", divName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "textDefaultType", textDefaultType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "idboxName", idboxName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "textboxName", textboxName);
            GetPartialTextDefaultOverride(callInfo, divName, textDefaultType, idboxName, textboxName);
            return callInfo;
        }

        [NonAction]
        partial void GetSelectTextDefaultOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Comision.Model.Enum.TextDefaultType type);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetSelectTextDefault(Comision.Model.Enum.TextDefaultType type)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetSelectTextDefault);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "type", type);
            GetSelectTextDefaultOverride(callInfo, type);
            return callInfo;
        }

        [NonAction]
        partial void ImageOverride(T4MVC_Comision_Ui_Models_Captcha_CaptchImageAction callInfo);

        [NonAction]
        public override Comision.Ui.Models.Captcha.CaptchImageAction Image()
        {
            var callInfo = new T4MVC_Comision_Ui_Models_Captcha_CaptchImageAction(Area, Name, ActionNames.Image);
            ImageOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ErrorOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? httpCode);

        [NonAction]
        public override System.Web.Mvc.ActionResult Error(int? httpCode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Error);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "httpCode", httpCode);
            ErrorOverride(callInfo, httpCode);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
