// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Comision.Ui.Areas.Personel.Controllers
{
    public partial class ReportController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ReportController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PrintCommision()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintCommision);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PrintCouncil()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintCouncil);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PrintCommisionAll()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintCommisionAll);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PrintCouncilAll()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintCouncilAll);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAllCommission()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllCommission);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAllCouncil()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllCouncil);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ReportController Actions { get { return MVC.Personel.Report; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Personel";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Report";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Report";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string ListRequestStudent = "ListRequestStudent";
            public readonly string CommisionAll = "CommisionAll";
            public readonly string CouncilAll = "CouncilAll";
            public readonly string PrintCommision = "PrintCommision";
            public readonly string PrintCouncil = "PrintCouncil";
            public readonly string PrintCommisionAll = "PrintCommisionAll";
            public readonly string PrintCouncilAll = "PrintCouncilAll";
            public readonly string GetReportCommission = "GetReportCommission";
            public readonly string GetReportAllCommission = "GetReportAllCommission";
            public readonly string GetReportAllCouncil = "GetReportAllCouncil";
            public readonly string GetAllCommission = "GetAllCommission";
            public readonly string GetAllCouncil = "GetAllCouncil";
            public readonly string GetReportCouncil = "GetReportCouncil";
            public readonly string ExportReport = "ExportReport";
            public readonly string ViewReport = "ViewReport";
            public readonly string ViewerEvent = "ViewerEvent";
            public readonly string PrintReport = "PrintReport";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string ListRequestStudent = "ListRequestStudent";
            public const string CommisionAll = "CommisionAll";
            public const string CouncilAll = "CouncilAll";
            public const string PrintCommision = "PrintCommision";
            public const string PrintCouncil = "PrintCouncil";
            public const string PrintCommisionAll = "PrintCommisionAll";
            public const string PrintCouncilAll = "PrintCouncilAll";
            public const string GetReportCommission = "GetReportCommission";
            public const string GetReportAllCommission = "GetReportAllCommission";
            public const string GetReportAllCouncil = "GetReportAllCouncil";
            public const string GetAllCommission = "GetAllCommission";
            public const string GetAllCouncil = "GetAllCouncil";
            public const string GetReportCouncil = "GetReportCouncil";
            public const string ExportReport = "ExportReport";
            public const string ViewReport = "ViewReport";
            public const string ViewerEvent = "ViewerEvent";
            public const string PrintReport = "PrintReport";
        }


        static readonly ActionParamsClass_ListRequestStudent s_params_ListRequestStudent = new ActionParamsClass_ListRequestStudent();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ListRequestStudent ListRequestStudentParams { get { return s_params_ListRequestStudent; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ListRequestStudent
        {
            public readonly string studentNumber = "studentNumber";
        }
        static readonly ActionParamsClass_PrintCommision s_params_PrintCommision = new ActionParamsClass_PrintCommision();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PrintCommision PrintCommisionParams { get { return s_params_PrintCommision; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PrintCommision
        {
            public readonly string commisionId = "commisionId";
        }
        static readonly ActionParamsClass_PrintCouncil s_params_PrintCouncil = new ActionParamsClass_PrintCouncil();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PrintCouncil PrintCouncilParams { get { return s_params_PrintCouncil; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PrintCouncil
        {
            public readonly string councilId = "councilId";
        }
        static readonly ActionParamsClass_PrintCommisionAll s_params_PrintCommisionAll = new ActionParamsClass_PrintCommisionAll();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PrintCommisionAll PrintCommisionAllParams { get { return s_params_PrintCommisionAll; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PrintCommisionAll
        {
            public readonly string searcvalue = "searcvalue";
            public readonly string searchtype = "searchtype";
        }
        static readonly ActionParamsClass_PrintCouncilAll s_params_PrintCouncilAll = new ActionParamsClass_PrintCouncilAll();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PrintCouncilAll PrintCouncilAllParams { get { return s_params_PrintCouncilAll; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PrintCouncilAll
        {
            public readonly string searcvalue = "searcvalue";
            public readonly string searchtype = "searchtype";
        }
        static readonly ActionParamsClass_GetAllCommission s_params_GetAllCommission = new ActionParamsClass_GetAllCommission();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAllCommission GetAllCommissionParams { get { return s_params_GetAllCommission; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAllCommission
        {
            public readonly string searcvalue = "searcvalue";
            public readonly string searchTypeid = "searchTypeid";
        }
        static readonly ActionParamsClass_GetAllCouncil s_params_GetAllCouncil = new ActionParamsClass_GetAllCouncil();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAllCouncil GetAllCouncilParams { get { return s_params_GetAllCouncil; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAllCouncil
        {
            public readonly string searcvalue = "searcvalue";
            public readonly string searchTypeid = "searchTypeid";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string CommisionAll = "CommisionAll";
                public readonly string CouncilAll = "CouncilAll";
                public readonly string ListRequestStudent = "ListRequestStudent";
                public readonly string ReportShow = "ReportShow";
            }
            public readonly string CommisionAll = "~/Areas/Personel/Views/Report/CommisionAll.cshtml";
            public readonly string CouncilAll = "~/Areas/Personel/Views/Report/CouncilAll.cshtml";
            public readonly string ListRequestStudent = "~/Areas/Personel/Views/Report/ListRequestStudent.cshtml";
            public readonly string ReportShow = "~/Areas/Personel/Views/Report/ReportShow.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ReportController : Comision.Ui.Areas.Personel.Controllers.ReportController
    {
        public T4MVC_ReportController() : base(Dummy.Instance) { }

        [NonAction]
        partial void ListRequestStudentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ListRequestStudent()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListRequestStudent);
            ListRequestStudentOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ListRequestStudentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long studentNumber);

        [NonAction]
        public override System.Web.Mvc.ActionResult ListRequestStudent(long studentNumber)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListRequestStudent);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "studentNumber", studentNumber);
            ListRequestStudentOverride(callInfo, studentNumber);
            return callInfo;
        }

        [NonAction]
        partial void CommisionAllOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CommisionAll()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CommisionAll);
            CommisionAllOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CouncilAllOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CouncilAll()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CouncilAll);
            CouncilAllOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PrintCommisionOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long commisionId);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintCommision(long commisionId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintCommision);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "commisionId", commisionId);
            PrintCommisionOverride(callInfo, commisionId);
            return callInfo;
        }

        [NonAction]
        partial void PrintCouncilOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long councilId);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintCouncil(long councilId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintCouncil);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "councilId", councilId);
            PrintCouncilOverride(callInfo, councilId);
            return callInfo;
        }

        [NonAction]
        partial void PrintCommisionAllOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string searcvalue, int searchtype);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintCommisionAll(string searcvalue, int searchtype)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintCommisionAll);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searcvalue", searcvalue);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchtype", searchtype);
            PrintCommisionAllOverride(callInfo, searcvalue, searchtype);
            return callInfo;
        }

        [NonAction]
        partial void PrintCouncilAllOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string searcvalue, int searchtype);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintCouncilAll(string searcvalue, int searchtype)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintCouncilAll);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searcvalue", searcvalue);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchtype", searchtype);
            PrintCouncilAllOverride(callInfo, searcvalue, searchtype);
            return callInfo;
        }

        [NonAction]
        partial void GetReportCommissionOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetReportCommission()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetReportCommission);
            GetReportCommissionOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetReportAllCommissionOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetReportAllCommission()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetReportAllCommission);
            GetReportAllCommissionOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetReportAllCouncilOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetReportAllCouncil()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetReportAllCouncil);
            GetReportAllCouncilOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetAllCommissionOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string searcvalue, int searchTypeid);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAllCommission(string searcvalue, int searchTypeid)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllCommission);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searcvalue", searcvalue);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchTypeid", searchTypeid);
            GetAllCommissionOverride(callInfo, searcvalue, searchTypeid);
            return callInfo;
        }

        [NonAction]
        partial void GetAllCouncilOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string searcvalue, int searchTypeid);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAllCouncil(string searcvalue, int searchTypeid)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllCouncil);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searcvalue", searcvalue);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchTypeid", searchTypeid);
            GetAllCouncilOverride(callInfo, searcvalue, searchTypeid);
            return callInfo;
        }

        [NonAction]
        partial void GetReportCouncilOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetReportCouncil()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetReportCouncil);
            GetReportCouncilOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ExportReportOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExportReport()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExportReport);
            ExportReportOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ViewReportOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ViewReport()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewReport);
            ViewReportOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ViewerEventOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ViewerEvent()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewerEvent);
            ViewerEventOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PrintReportOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintReport()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintReport);
            PrintReportOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
