// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Comision.Ui.Areas.Personel.Controllers
{
    public partial class RequestController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RequestController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DetailRequest()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DetailRequest);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DetailRequestPartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DetailRequestPartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetListSpecialEducationforRequest()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetListSpecialEducationforRequest);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetRequestByStudentCode()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetRequestByStudentCode);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetFollowByRequestId()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetFollowByRequestId);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Archive()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Archive);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteRequest()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteRequest);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public RequestController Actions { get { return MVC.Personel.Request; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Personel";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Request";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Request";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string DetailRequest = "DetailRequest";
            public readonly string DetailRequestPartial = "DetailRequestPartial";
            public readonly string GetListSpecialEducationforRequest = "GetListSpecialEducationforRequest";
            public readonly string GetListRequest = "GetListRequest";
            public readonly string FollowUp = "FollowUp";
            public readonly string GetRequestByStudentCode = "GetRequestByStudentCode";
            public readonly string GetFollowByRequestId = "GetFollowByRequestId";
            public readonly string Archive = "Archive";
            public readonly string DeleteRequest = "DeleteRequest";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string DetailRequest = "DetailRequest";
            public const string DetailRequestPartial = "DetailRequestPartial";
            public const string GetListSpecialEducationforRequest = "GetListSpecialEducationforRequest";
            public const string GetListRequest = "GetListRequest";
            public const string FollowUp = "FollowUp";
            public const string GetRequestByStudentCode = "GetRequestByStudentCode";
            public const string GetFollowByRequestId = "GetFollowByRequestId";
            public const string Archive = "Archive";
            public const string DeleteRequest = "DeleteRequest";
        }


        static readonly ActionParamsClass_DetailRequest s_params_DetailRequest = new ActionParamsClass_DetailRequest();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DetailRequest DetailRequestParams { get { return s_params_DetailRequest; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DetailRequest
        {
            public readonly string requestId = "requestId";
            public readonly string postId = "postId";
            public readonly string rowNumber = "rowNumber";
            public readonly string lastCommissionSigner = "lastCommissionSigner";
            public readonly string lastCouncilSigner = "lastCouncilSigner";
            public readonly string rootUrl = "rootUrl";
        }
        static readonly ActionParamsClass_DetailRequestPartial s_params_DetailRequestPartial = new ActionParamsClass_DetailRequestPartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DetailRequestPartial DetailRequestPartialParams { get { return s_params_DetailRequestPartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DetailRequestPartial
        {
            public readonly string requestId = "requestId";
        }
        static readonly ActionParamsClass_GetListSpecialEducationforRequest s_params_GetListSpecialEducationforRequest = new ActionParamsClass_GetListSpecialEducationforRequest();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetListSpecialEducationforRequest GetListSpecialEducationforRequestParams { get { return s_params_GetListSpecialEducationforRequest; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetListSpecialEducationforRequest
        {
            public readonly string requestId = "requestId";
        }
        static readonly ActionParamsClass_GetRequestByStudentCode s_params_GetRequestByStudentCode = new ActionParamsClass_GetRequestByStudentCode();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetRequestByStudentCode GetRequestByStudentCodeParams { get { return s_params_GetRequestByStudentCode; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetRequestByStudentCode
        {
            public readonly string stNumber = "stNumber";
        }
        static readonly ActionParamsClass_GetFollowByRequestId s_params_GetFollowByRequestId = new ActionParamsClass_GetFollowByRequestId();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetFollowByRequestId GetFollowByRequestIdParams { get { return s_params_GetFollowByRequestId; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetFollowByRequestId
        {
            public readonly string reqId = "reqId";
        }
        static readonly ActionParamsClass_Archive s_params_Archive = new ActionParamsClass_Archive();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Archive ArchiveParams { get { return s_params_Archive; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Archive
        {
            public readonly string requestId = "requestId";
        }
        static readonly ActionParamsClass_DeleteRequest s_params_DeleteRequest = new ActionParamsClass_DeleteRequest();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteRequest DeleteRequestParams { get { return s_params_DeleteRequest; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteRequest
        {
            public readonly string requestId = "requestId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _DetailRequest = "_DetailRequest";
                public readonly string _FollowRequests = "_FollowRequests";
                public readonly string _FollowUpDetail = "_FollowUpDetail";
                public readonly string DetailRequest = "DetailRequest";
                public readonly string FollowUp = "FollowUp";
                public readonly string Index = "Index";
            }
            public readonly string _DetailRequest = "~/Areas/Personel/Views/Request/_DetailRequest.cshtml";
            public readonly string _FollowRequests = "~/Areas/Personel/Views/Request/_FollowRequests.cshtml";
            public readonly string _FollowUpDetail = "~/Areas/Personel/Views/Request/_FollowUpDetail.cshtml";
            public readonly string DetailRequest = "~/Areas/Personel/Views/Request/DetailRequest.cshtml";
            public readonly string FollowUp = "~/Areas/Personel/Views/Request/FollowUp.cshtml";
            public readonly string Index = "~/Areas/Personel/Views/Request/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_RequestController : Comision.Ui.Areas.Personel.Controllers.RequestController
    {
        public T4MVC_RequestController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DetailRequestOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long requestId, long postId, long rowNumber, int lastCommissionSigner, int lastCouncilSigner, string rootUrl);

        [NonAction]
        public override System.Web.Mvc.ActionResult DetailRequest(long requestId, long postId, long rowNumber, int lastCommissionSigner, int lastCouncilSigner, string rootUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DetailRequest);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "requestId", requestId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "postId", postId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rowNumber", rowNumber);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lastCommissionSigner", lastCommissionSigner);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lastCouncilSigner", lastCouncilSigner);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rootUrl", rootUrl);
            DetailRequestOverride(callInfo, requestId, postId, rowNumber, lastCommissionSigner, lastCouncilSigner, rootUrl);
            return callInfo;
        }

        [NonAction]
        partial void DetailRequestPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long requestId);

        [NonAction]
        public override System.Web.Mvc.ActionResult DetailRequestPartial(long requestId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DetailRequestPartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "requestId", requestId);
            DetailRequestPartialOverride(callInfo, requestId);
            return callInfo;
        }

        [NonAction]
        partial void GetListSpecialEducationforRequestOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long requestId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetListSpecialEducationforRequest(long requestId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetListSpecialEducationforRequest);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "requestId", requestId);
            GetListSpecialEducationforRequestOverride(callInfo, requestId);
            return callInfo;
        }

        [NonAction]
        partial void GetListRequestOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetListRequest()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetListRequest);
            GetListRequestOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void FollowUpOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult FollowUp()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FollowUp);
            FollowUpOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetRequestByStudentCodeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long stNumber);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetRequestByStudentCode(long stNumber)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetRequestByStudentCode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "stNumber", stNumber);
            GetRequestByStudentCodeOverride(callInfo, stNumber);
            return callInfo;
        }

        [NonAction]
        partial void GetFollowByRequestIdOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long reqId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetFollowByRequestId(long reqId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetFollowByRequestId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "reqId", reqId);
            GetFollowByRequestIdOverride(callInfo, reqId);
            return callInfo;
        }

        [NonAction]
        partial void ArchiveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long requestId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Archive(long requestId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Archive);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "requestId", requestId);
            ArchiveOverride(callInfo, requestId);
            return callInfo;
        }

        [NonAction]
        partial void DeleteRequestOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long requestId);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteRequest(long requestId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteRequest);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "requestId", requestId);
            DeleteRequestOverride(callInfo, requestId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
