///////////////////////////////////////////////////////////
//  Cartable.cs
//  Implementation of the Class Cartable
//  Generated by Enterprise Architect
//  Created on:      09-Jun-2016 8:23:08 AM
//  Original author: ali-laptop
///////////////////////////////////////////////////////////

using System.ComponentModel.DataAnnotations.Schema;
using Comision.Model.Common;
using Comision.Model.Enum;

namespace Comision.Model.Domain
{
    /// <summary>
    /// <span dir="rtl">تاييد درخواست</span>
    /// </summary>
    public class Cartable : AuditableEntity<long>
    {
        [Index("IX_Cartable", IsUnique = true, Order = 1)]
        public long RequestId { get; set; }
        public virtual Request Request { get; set; }
        public long PersonId { get; set; }
        public virtual Person Person { get; set; }
        /// <summary>
        /// ایدی پرسنل از طرف
        /// </summary>
        public long PersonIdOnBehalfof { get; set; }
        /// <summary>
        /// پرسنل از طرف
        /// </summary>
        public virtual Person PersonOnBehalfof { get; set; }

        [Index("IX_Cartable", IsUnique = true, Order = 2)]
        public long PostId { get; set; }
        public virtual Post Post { get; set; }

        [Index("IX_Cartable", IsUnique = true, Order = 3)]
        public CartableStatus CartableStatus { get; set; }

        [Index("IX_Cartable", IsUnique = true, Order = 4)]
        public CartableValidation CartableValidation { get; set; }

        [Index("IX_Cartable", IsUnique = true, Order = 5)]
        public int RowNumber { get; set; }

        [Index("IX_Cartable", IsUnique = true, Order = 6)]
        public int Series { get; set; }
        public bool ReferTo { get; set; }
        public string Description { get; set; }
        public Cartable() { }

      

    }//end Cartable
}