///////////////////////////////////////////////////////////
//  Personel.cs
//  Implementation of the Class Personel
//  Generated by Enterprise Architect
//  Created on:      09-Jun-2016 8:22:45 AM
//  Original author: ali-laptop
///////////////////////////////////////////////////////////

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Comision.Model.Common;
using Comision.Model.Enum;

namespace Comision.Model.Domain
{
    /// <summary>
    /// <span dir="rtl">پرسنل</span>
    /// </summary>
    public class Personel : Auditable
    {
        /// <summary>
        /// ایدی شخص
        /// کلید اصلی و خارجی
        /// </summary>
        public long PersonId { get; set; }

        /// <summary>
        /// شی شخص
        /// </summary>
        public virtual Person Person { get; set; }

        /// <summary>
        /// شماره کارمندی
        /// فعلا غیر فعال شد تا اجباری نباشد 
        /// </summary>
      //  [Index("IX_EmployeeNumber", IsUnique = true)]
        public string EmployeeNumber { get; set; }

        /// <summary>
        /// تاریخ استخدام
        /// </summary>
        [UIHint("PersianDatePicker")]
        public DateTime? DateOfEmployeement { get; set; }

        /// <summary>
        /// امضای الکترونیکی
        /// </summary>
        public virtual string Signature { get; set; }

        /// <summary>
        /// فعال/غیر فعال
        /// </summary>
        public virtual bool Active { get; set; }

        /// <summary>
        /// آخرین مدرک تحصیلی
        /// </summary>
        public Grade Grade { get; set; }

        public Personel() { }
    }//end Personel
}