///////////////////////////////////////////////////////////
//  Signer.cs
//  Implementation of the Class Signer
//  Generated by Enterprise Architect
//  Created on:      09-Jun-2016 8:23:22 AM
//  Original author: ali-laptop
///////////////////////////////////////////////////////////

using System.ComponentModel.DataAnnotations.Schema;
using Comision.Model.Common;
using Comision.Model.Enum;

namespace Comision.Model.Domain
{
    /// <summary>
    /// <span dir="rtl">«„÷« ò‰‰œê«‰ ‘Ê—« Ê ò„Ì”ÌÊ‰</span>
    /// </summary>
    public class Signer : AuditableEntity<long>
    {
        public long PostId { get; set; }
        public virtual Post Post { get; set; }

        [Index("IX_RowNumber", IsUnique = true,Order = 1)]
        public RequestType RequestType { get; set; }

        [Index("IX_RowNumber", IsUnique = true,Order=2)]
        public int RowNumber { get; set; }

        public Signer() { }

    }//end Signer
}