///////////////////////////////////////////////////////////
//  RequestType.cs
//  Implementation of the Enumeration RequestType
//  Generated by Enterprise Architect
//  Created on:      09-Jun-2016 8:23:11 AM
//  Original author: ali-laptop
///////////////////////////////////////////////////////////

using System.ComponentModel;

namespace Comision.Model.Enum
{
    /// <summary>
    /// <span dir="rtl">نوع درخواست</span>
    /// </summary>
    public enum RequestType : int
    {
        /// <summary>
        /// <span dir="rtl">کمیسیون موارد خاص</span>
        /// </summary>
        [Description("کمیسیون موارد خاص")]
        Comision=1,

        /// <summary>
        /// <span dir="rtl">شورای آموزشی</span>
        /// </summary>
        [Description("شورای آموزشی")]
        Council

    }//end RequestType
}