///////////////////////////////////////////////////////////
//  UserState.cs
//  Implementation of the Enumeration UserState
//  Generated by Enterprise Architect
//  Created on:      09-Jun-2016 8:23:40 AM
//  Original author: ali-laptop
///////////////////////////////////////////////////////////

using System.ComponentModel;

namespace Comision.Model.Enum
{
    /// <summary>
    /// <span dir="rtl">وضعیت کاربر</span>
    /// </summary>
    public enum UserState : int
    {
        /// <summary>
        /// <span dir="rtl">فعال</span>
        /// </summary>
        [Description("فعال")]
        Active=1,

        /// <summary>
        /// <span dir="rtl">غير فعال</span>
        /// </summary>
        [Description("غير فعال")]
        NotActive,

        /// <summary>
        /// <span dir="rtl">بلاک</span>
        /// </summary>
        [Description("بلاک")]
        Block

    }//end UserState
}